logging.level:
  com.netflix.discovery: 'OFF'

zuul.sensitive-headers: Cookie,Set-Cookie

security:
  ignored: /security/**
  oauth2.resource:
    user-info-uri: http://security/user
    load-balanced: true